name: Test Auto Rebase

# The following line was suspect to be the culprit but it turned out
# not to be.
# run-name: Testing PR no.${{ github.event.pull_request.number }}

on: 
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted]

permissions:
  id-token: write
  contents: write
  actions: read
  pull-requests: write

jobs:
  Test-Auto-Rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.HPPUSHPAT }}
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Rebase if necessary
        env:
          GITHUB_TOKEN: ${{ secrets.HPPUSHPAT }}
        run: |
          behind=$(git rev-list --count @..origin/master)
          echo "This PR is $behind commits behind master."
          if [[ $behind -gt 0 ]]; then
            echo "Merging master..."
            git config user.email "HotPirsch@users.noreply.github.com"
            git config user.name "Hotpirsch"
            git fetch origin
            git merge origin/master -m "Merging master into ${{ github.event.pull_request.head.ref }}"
            git push
          fi
