name: Test Auto Rebase

run-name: Testing PR no.${{ github.event.pull_request.number }}

on: 
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted]

permissions:
  id-token: write
  contents: write
  actions: read
  pull-requests: write

jobs:
  Test-Auto-Rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Rebase if necessary
        run: |
          behind=$(git rev-list --count @..origin/master)
          echo "This PR is $behind commits behind master."
          if [[ $behind -gt 0 ]]; then
            echo "Merging maaster..."
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git config user.name "github-actions[bot]"
            git fetch origin
            git merge origin/master -m "Merging master into ${{ github.event.pull_request.head.ref }}"
            git push
          fi
